### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by benisdev-py** [MatthewVance/unbound-docker-rpi#15]
hi, how can I change the port so that unbound is lisining on port 5113

I use this config:
`docker run \
--name=unbound-rpi \
--publish=5113:53/udp \
--publish=5113:53/tcp \
--restart=always \
--detach=true \
mvance/unbound-rpi:latest`

As you see in the picture they say Cannot assign requested address on port 53

![grafik](https://user-images.githubusercontent.com/77000141/119633808-64841a80-be12-11eb-815f-36d90435db2a.png)

**Comment by MatthewVance** [comment]
hi, the error you are seeing is unrelated. Unbound will continue to run on port 53 inside the container. 5113 will be what's published externally. It's likely a manifestation of this upstream issue: https://github.com/NLnetLabs/unbound/issues/364

**Comment by kunalnagar** [comment]
@MatthewVance - just looking to get some info on a next step here. I'm using the latest (1.14.0) version of your image on a RaspBerry pi4 with a different port as well and still facing the problem even though the issue upstream seems to be resolved. Is there something I'm missing?

**Comment by MatthewVance** [comment]
Changing ports on IPv4 works. IPv6 is not supported for this image. Unless I’m missing something, the error is about IPv6 and should not be occurring if the upstream issue was fully resolved. 

I still think it is an upstream issue because this UDP connect error didn’t exist on earlier releases of Unbound (pre 1.30.0) with essentially the same image settings. 

Why would an IPv6 error be occurring in containers running this image if IPv6 support is turned off (interface is only listening on IPv4) unless it is an upstream issue?
https://github.com/MatthewVance/unbound-docker-rpi/blob/c04b389805caacab2a69ea06db69a681cb2abb19/1.14.0/data/unbound.sh#L74

Upstream is likely resolved if not running on Docker. Docker’s handling of IPv6 is unique and complex, thus this is probably triggering an edge case in the upstream code. 

One thing that comes to mind that may be worth trying is to add these extra config flags:
do-ip6: no
prefer-ip4: yes
prefer-ip6: no
I’m not trying to be difficult but only explain the issue as I understand it. I know it’s frustrating, I’d rather not have those errors in my log either. 
It’s entirely possible I’m missing something. If someone finds and presents a configuration change that resolves this error, I’m glad to implement it.
